backend:
  image: shreybatra/sample-backend
  replicaCount: 1
  service:
    name: backend-svc
    type: ClusterIP
    port: 8000
  env:
    REDIS_URI: redis://redis-svc:6379

frontend:
  image: shreybatra/sample-frontend
  replicaCount: 1
  service:
    name: frontend-svc
    type: NodePort
    port: 5173
    nodePort: 31000
  env:
    BACKEND_URL: http://backend-svc:8000

redis:
  image: redis
  replicaCount: 1
  service:
    name: redis-svc
    type: ClusterIP
    port: 6379

